#!/usr/bin/env python3
"""
CoBa's Daughter - Broad (Self-Care & Gifting) Static Ad System
Single source of truth for the 100-ad matrix.

Run:  python3 generate_ads.py
Outputs (next to this file):
  - bulk-create-1x1.csv     -> upload to the 1:1 Canva Bulk Create template
  - bulk-create-9x16.csv    -> upload to the 9:16 Canva Bulk Create template
  - 100-ads.md              -> human-readable review matrix

Funnel mix: 40 MOF / 60 BOF  (per brief)
Rule: ONE promo per BOF ad. MOF ads carry a Reason-To-Believe, never a price.
Each row's columns map 1:1 to connectable text fields in the Canva template.
"""

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Field guide (these become the connected data fields in Canva Bulk Create):
#   headline  -> the scroll-stopping hook (largest text layer)
#   subhead   -> the supporting line / payoff (medium text layer)
#   badge     -> RTB chip (MOF) OR the single offer chip (BOF)  [pill/tag layer]
#   cta       -> button label (CTA layer)
#   product   -> product name shown on the design (small caption layer)
#   visual    -> art-direction note for the image you drop in (NOT printed)
# ---------------------------------------------------------------------------

ADS = [
    # ===================== MOF (40) — RTB-led, no price =====================
    # --- ANGLE: THE RITUAL (slow living / make the shower a ritual) ---
    ("M-RITUAL", "Make it a ritual", "MOF",
     "Your shower called. It wants to be a ritual.",
     "Ten quiet minutes that feel like a small vacation for your skin.",
     "Cold-pressed coffee + raw cane sugar", "Discover the ritual",
     "Coffee Scrub", "Steam, warm bathroom light, a hand scooping scrub from the jar"),
    ("M-RITUAL", "Make it a ritual", "MOF",
     "Self-care isn't selfish. It's maintenance.",
     "Begin and end the day with something that's only for you.",
     "Ritual body care", "Start the ritual",
     "Body care range", "Candle + scrub jar styled on a rattan tray"),
    ("M-RITUAL", "Make it a ritual", "MOF",
     "The five minutes that change the other 23 hours.",
     "A scrub-and-soak ritual to reset, slowly.",
     "Slow body care", "Build your ritual",
     "Coffee Scrub + Soap", "Bath, linen, soft morning light"),
    ("M-RITUAL", "Make it a ritual", "MOF",
     "Romanticize the mundane. Start with your shower.",
     "Texture, warmth, scent — small luxuries that add up.",
     "Everyday ritual", "Explore the ritual",
     "Coffee Scrub", "Water droplets catching light on skin"),
    ("M-RITUAL", "Heritage ritual", "MOF",
     "Some rituals are inherited. This one's worth keeping.",
     "Body care made the slow way — the way it was meant to be.",
     "Rooted in heritage", "Discover CoBa's Daughter",
     "Brand range", "Hands, rattan, warm earthy tones"),
    ("M-RITUAL", "PM wind-down", "MOF",
     "Wash the day off. Properly.",
     "A grounding end-of-day ritual for skin that's had enough.",
     "Evening ritual", "Shop the ritual",
     "Soap + Scrub", "Night scene, candle, folded towel"),
    ("M-RITUAL", "Glow is a habit", "MOF",
     "Glow is a habit, not an accident.",
     "Two minutes of scrub, three times a week. That's it.",
     "The 2-minute ritual", "Start glowing",
     "Coffee Scrub", "Glowing shoulder, golden light"),
    ("M-RITUAL", "Beautiful bathroom", "MOF",
     "Make your bathroom the nicest room in the house.",
     "Objects and rituals worth slowing down for.",
     "Considered body care", "Explore the collection",
     "Range + Rattan", "Styled rattan shelf with products"),

    # --- ANGLE: SENSORY ESCAPE (scent / texture / aromatherapy) ---
    ("M-SENSE", "Scent story", "MOF",
     "It smells like a slow morning in a warm kitchen.",
     "Real coffee, raw sugar — nothing synthetic pretending to be.",
     "Cold-pressed coffee scent", "Smell for yourself",
     "Coffee Scrub", "Macro of scrub texture with coffee grounds"),
    ("M-SENSE", "Texture proof", "MOF",
     "Texture you can feel working.",
     "Grains that melt as they buff — never sandpaper, never slip.",
     "Sugar + coffee grain", "Feel the difference",
     "Coffee Scrub", "Scrub on fingertips, extreme macro"),
    ("M-SENSE", "Aromatherapy", "MOF",
     "Aromatherapy, minus the woo.",
     "Scents that actually slow your breathing down.",
     "Mood: unbothered", "Find your scent",
     "Soap Trio", "Soap bars with botanicals, soft styling"),
    ("M-SENSE", "Cooling sensory", "MOF",
     "The first cold gel of summer on warm skin.",
     "Instant relief that sinks in — never sticky.",
     "Pure aloe, cooling", "Cool down",
     "Aloe Gel", "Gel on shoulder, dewy skin"),
    ("M-SENSE", "Escape", "MOF",
     "Close your eyes. You're not in the shower anymore.",
     "Scent that takes you somewhere, even on a Tuesday.",
     "Sensory body care", "Escape daily",
     "Range", "Steam, eyes closed, serene"),
    ("M-SENSE", "Smells expensive", "MOF",
     "Skin that smells expensive. (Quietly.)",
     "The kind of scent people lean in to ask about.",
     "Signature scent", "Discover the scent",
     "Range", "Close skin, golden hour glow"),
    ("M-SENSE", "Addictive cool", "MOF",
     "Cool, clean, and a little addictive.",
     "Aloe gel that disappears into skin — and takes the heat with it.",
     "Lightweight aloe", "Try the gel",
     "Aloe Gel", "Gel texture macro, fresh"),
    ("M-SENSE", "Coffee mood", "MOF",
     "Coffee for your skin, not your nerves.",
     "All the ritual of your morning cup, none of the jitters.",
     "Cold-pressed coffee", "Wake up your skin",
     "Coffee Scrub", "Coffee cup + scrub jar flatlay"),

    # --- ANGLE: VISIBLE RESULTS (smoothness / glow / RTB) ---
    ("M-RESULT", "Fast smooth", "MOF",
     "Smoother in one shower. We timed it.",
     "Buff away the dull, reveal the skin that was always there.",
     "Exfoliate + nourish", "See the glow",
     "Coffee Scrub", "Before/after texture on a leg"),
    ("M-RESULT", "Bumpy arms", "MOF",
     "Goodbye, bumpy arms.",
     "Gentle exfoliation for the rough patches nobody talks about.",
     "Smooths rough + bumpy skin", "Smooth it out",
     "Coffee Scrub", "Upper-arm close-up, smooth result"),
    ("M-RESULT", "Razor bumps", "MOF",
     "Razor bumps didn't stand a chance.",
     "Exfoliate before, soothe after — smooth, settled skin.",
     "Pre-shave + post-shave", "See how",
     "Coffee Scrub + Aloe Gel", "Smooth legs, clean styling"),
    ("M-RESULT", "Compliment glow", "MOF",
     "The 'what are you using?' kind of glow.",
     "Soft, lit-from-within skin from the neck down.",
     "Visible glow", "Get the glow",
     "Coffee Scrub", "Glowing décolleté, natural light"),
    ("M-RESULT", "Tan prep", "MOF",
     "Self-tan, but make it even.",
     "Exfoliate first and watch your glow go on flawless.",
     "Preps for an even glow", "Prep + glow",
     "Coffee Scrub", "Smooth, evenly-tanned legs"),
    ("M-RESULT", "After-sun", "MOF",
     "Sunburn's worst enemy.",
     "Pure aloe that calms the heat and saves the weekend.",
     "Cooling relief", "Soothe skin",
     "Aloe Gel", "Shoulder with aloe, soft focus"),
    ("M-RESULT", "Body = face", "MOF",
     "Soft enough to notice. Every time you sit down.",
     "Body skin that finally feels as cared-for as your face.",
     "Nourished, not stripped", "Feel softer",
     "Exfoliate & Nourish Set", "Hand resting on soft thigh"),
    ("M-RESULT", "Routine", "MOF",
     "Your body skincare routine has been waiting.",
     "Exfoliate, nourish, repeat — results you can feel.",
     "Body skincare", "Build the routine",
     "Exfoliate & Nourish Set", "Set flatlay, editorial"),

    # --- ANGLE: MADE WITH INTENTION (clean / craft / ingredients RTB) ---
    ("M-CLEAN", "Short list", "MOF",
     "Ingredients you can pronounce. That's the point.",
     "Coffee, sugar, oil — nothing to hide.",
     "Clean by design", "Read the label",
     "Coffee Scrub", "Ingredients laid out neatly on stone"),
    ("M-CLEAN", "Slow made", "MOF",
     "Made the slow way. On purpose.",
     "Small batches, real ingredients, no shortcuts.",
     "Small batch", "Meet the maker",
     "Brand", "Hands at work, craft, rattan"),
    ("M-CLEAN", "Food-grade", "MOF",
     "If it's not good enough to eat, it's not going on your skin.",
     "Food-grade ingredients, head to toe.",
     "Food-grade", "See what's inside",
     "Coffee Scrub", "Coffee beans + raw sugar styled"),
    ("M-CLEAN", "Free-from", "MOF",
     "No synthetic fragrance. No fake glow. No filler.",
     "Just what your skin actually wants.",
     "Free from the nonsense", "Shop clean",
     "Range", "Minimalist single-product still life"),
    ("M-CLEAN", "Real aloe", "MOF",
     "The aloe inside is actually aloe.",
     "Not water with a green tint and a promise.",
     "Real aloe, high %", "Check the gel",
     "Aloe Gel", "Cut aloe leaf beside the tube"),
    ("M-CLEAN", "Cruelty-free", "MOF",
     "Cruelty-free, because obviously.",
     "Kind to skin, kinder to everything else.",
     "Cruelty-free", "Learn more",
     "Brand", "Soft, ethical, natural styling"),
    ("M-CLEAN", "Nothing extra", "MOF",
     "We left out everything your skin doesn't need.",
     "And kept the ingredients that earn their place.",
     "Intentional formulas", "Discover why",
     "Range", "Clean flatlay on neutral linen"),
    ("M-CLEAN", "Heritage jar", "MOF",
     "Heritage in a jar.",
     "Rooted in Vietnamese ritual, made for everyday skin.",
     "Crafted with heritage", "Discover the story",
     "Brand", "Rattan, coffee, heritage cues"),

    # --- ANGLE: THE CONSIDERED GIFT (emotional gifting, no price) ---
    ("M-GIFT", "Thoughtful", "MOF",
     "The gift that says 'I actually thought about this.'",
     "Beautiful enough to give. Good enough they'll rebuy.",
     "Giftable body care", "Explore gifts",
     "Rattan Valise", "Wrapped rattan valise, ribbon"),
    ("M-GIFT", "Not another candle", "MOF",
     "Skip the candle. Again.",
     "A gift she'll use every single day — not shelve.",
     "Gifts that get used", "Find the gift",
     "Exfoliate & Nourish Set", "Set styled as a gift"),
    ("M-GIFT", "Keepsake", "MOF",
     "Hand-woven rattan, filled with the good stuff.",
     "A keepsake basket she'll keep long after.",
     "Rattan keepsake", "See the gift sets",
     "Rattan Basket", "Rattan basket gift, overhead"),
    ("M-GIFT", "Their turn", "MOF",
     "For the person who buys everyone else's gifts.",
     "It's their turn — make it easy and make it beautiful.",
     "Considered gifting", "Shop gifts",
     "Rattan Valise", "Elegant gift moment"),
    ("M-GIFT", "Travels well", "MOF",
     "A gift that travels well.",
     "The Rattan Valise looks as good on a shelf as in a suitcase.",
     "The Rattan Valise", "Discover the valise",
     "Rattan Valise", "Valise styled with travel cues"),
    ("M-GIFT", "Anniversary", "MOF",
     "Anniversaries deserve more than flowers that die.",
     "Give a ritual that lasts longer than a bouquet.",
     "Anniversary gifting", "Find the gift",
     "Gift Set", "Romantic set with flowers"),
    ("M-GIFT", "Gift-ready", "MOF",
     "Wrapped, ribboned, and ready to impress.",
     "Gifting handled — you just sign the card.",
     "Gift-ready", "Explore gift sets",
     "Gift Set", "Ribbon and wrapping detail"),
    ("M-GIFT", "Foolproof", "MOF",
     "Give the glow, not the guesswork.",
     "A body care set anyone will be happy to unwrap.",
     "Foolproof gift", "Shop the set",
     "Exfoliate & Nourish Set", "Set as a gift, clean"),

    # ===================== BOF (60) — ONE promo per ad =====================
    # --- ANGLE: SCRUB DUO ($69 was $84, save $15) ---
    ("B-SCRUBDUO", "Save $15", "BOF",
     "Two scrubs. One smoother you.",
     "The Scrub Duo is $69 (was $84).",
     "Scrub Duo · Save $15", "Shop the Scrub Duo",
     "Scrub Duo", "Two coffee scrub jars side by side"),
    ("B-SCRUBDUO", "Double glow", "BOF",
     "Double the glow for $15 less.",
     "Our bestselling scrub, now in a duo.",
     "$69 (was $84)", "Get the duo",
     "Scrub Duo", "Duo flatlay on linen"),
    ("B-SCRUBDUO", "Keep+give", "BOF",
     "One for the shower. One for the gift bag.",
     "Scrub Duo, $69 — keep one, give one.",
     "Save $15", "Shop the duo",
     "Scrub Duo", "Two jars, one tied with ribbon"),
    ("B-SCRUBDUO", "Stock up", "BOF",
     "Never run out of your favorite scrub again.",
     "Stock up with the Scrub Duo and save $15.",
     "Scrub Duo · $69", "Stock up now",
     "Scrub Duo", "Two jars stacked"),
    ("B-SCRUBDUO", "Twice over", "BOF",
     "Smooth skin, twice over.",
     "The Scrub Duo: $69 instead of $84.",
     "Save $15", "Buy the duo",
     "Scrub Duo", "Glowing skin beside the duo"),
    ("B-SCRUBDUO", "Bestseller duo", "BOF",
     "Your bestseller, now buy-in-twos.",
     "Two coffee scrubs for $69. Save $15.",
     "Bestseller · Save $15", "Shop now",
     "Scrub Duo", "Duo with bestseller tag"),
    ("B-SCRUBDUO", "Urgency", "BOF",
     "The duo that disappears fastest.",
     "Scrub Duo, $69 (was $84) — while it lasts.",
     "Save $15", "Grab the duo",
     "Scrub Duo", "Two jars, warm light"),
    ("B-SCRUBDUO", "Easy math", "BOF",
     "$15 off your smoothest skin yet.",
     "Two coffee scrubs. One easy decision.",
     "Scrub Duo · $69", "Shop the Scrub Duo",
     "Scrub Duo", "Macro scrub + duo"),

    # --- ANGLE: ALOE DUO ($59 was $64, save $5) ---
    ("B-ALOEDUO", "Save $5", "BOF",
     "Cool skin, doubled.",
     "The Aloe Duo is $59 (was $64).",
     "Aloe Duo · Save $5", "Shop the Aloe Duo",
     "Aloe Duo", "Two aloe tubes side by side"),
    ("B-ALOEDUO", "Home+away", "BOF",
     "One by the bed. One in the bag.",
     "Aloe Duo, $59 — cooling relief, everywhere.",
     "Save $5", "Get the duo",
     "Aloe Duo", "Two tubes, lifestyle"),
    ("B-ALOEDUO", "Sunburn season", "BOF",
     "Sunburn season, sorted.",
     "Two aloe gels for $59. Be ready.",
     "Aloe Duo · $59", "Stock up now",
     "Aloe Duo", "Beach scene with aloe"),
    ("B-ALOEDUO", "Cool-down", "BOF",
     "Twice the cool-down for $5 less.",
     "The Aloe Duo: $59 instead of $64.",
     "Save $5", "Buy the duo",
     "Aloe Duo", "Gel macro, fresh"),
    ("B-ALOEDUO", "Never search", "BOF",
     "Never search for your aloe again.",
     "Aloe Duo, $59 — one for home, one for away.",
     "Aloe Duo · Save $5", "Shop now",
     "Aloe Duo", "Two tubes flatlay"),
    ("B-ALOEDUO", "Buy in twos", "BOF",
     "Cooling relief, buy-in-twos.",
     "Two pure aloe gels for $59.",
     "Save $5", "Grab the duo",
     "Aloe Duo", "Aloe leaf + two tubes"),
    ("B-ALOEDUO", "After-sun", "BOF",
     "The after-sun your skin will thank you for.",
     "Aloe Duo, $59 (was $64).",
     "Aloe Duo · $59", "Soothe + save",
     "Aloe Duo", "Shoulder with aloe"),
    ("B-ALOEDUO", "In pairs", "BOF",
     "Hydration that travels in pairs.",
     "Two aloe gels, $59. Save $5.",
     "Save $5", "Shop the Aloe Duo",
     "Aloe Duo", "Tubes flatlay, clean"),

    # --- ANGLE: SOAP TRIO (Buy 3 for 2, $72 was $108) ---
    ("B-SOAPTRIO", "Buy 3 for 2", "BOF",
     "Buy 3, pay for 2.",
     "The 3-in-1 Soap Trio: $72 instead of $108.",
     "Buy 3 For 2", "Shop the trio",
     "3in1 Soap Trio", "Three soap bars stacked"),
    ("B-SOAPTRIO", "Save $36", "BOF",
     "Three soaps. The price of two.",
     "Soap Trio, $72 — save $36.",
     "Save $36", "Get the trio",
     "3in1 Soap Trio", "Stacked bars on stone"),
    ("B-SOAPTRIO", "Never enough", "BOF",
     "One bar's never enough. Good thing there's three.",
     "Buy 3 for 2 — Soap Trio, $72.",
     "Buy 3 For 2", "Shop now",
     "3in1 Soap Trio", "Bars with botanicals"),
    ("B-SOAPTRIO", "Repeat", "BOF",
     "Cleanse, lather, repeat — three times over.",
     "The Soap Trio is $72 (was $108).",
     "Save $36", "Buy the trio",
     "3in1 Soap Trio", "Lather + bars"),
    ("B-SOAPTRIO", "Keep+gift", "BOF",
     "Keep one. Gift two. (Or keep all three.)",
     "Buy 3 for 2: Soap Trio, $72.",
     "Buy 3 For 2", "Shop the trio",
     "3in1 Soap Trio", "Three bars, one wrapped"),
    ("B-SOAPTRIO", "Third free", "BOF",
     "Your free third bar is waiting.",
     "Soap Trio: buy 3 for 2, just $72.",
     "3rd Bar Free", "Claim it",
     "3in1 Soap Trio", "Three bars, spotlight on one"),
    ("B-SOAPTRIO", "Spa x3", "BOF",
     "The soap that turns showers into spa time. ×3.",
     "$72 for three. Save $36.",
     "Buy 3 For 2", "Get the trio",
     "3in1 Soap Trio", "Spa styling with bars"),
    ("B-SOAPTRIO", "Stock dish", "BOF",
     "Stock the soap dish for a season.",
     "Buy 3 for 2 — Soap Trio, $72 (was $108).",
     "Save $36", "Shop the Soap Trio",
     "3in1 Soap Trio", "Styled soap dish"),

    # --- ANGLE: FREE US SHIPPING ($50+) ---
    ("B-SHIP", "Ships free", "BOF",
     "Your glow ships free.",
     "Free US shipping on orders $50+.",
     "Free US Shipping $50+", "Shop now",
     "Bestsellers", "Package with rattan + products"),
    ("B-SHIP", "Add one more", "BOF",
     "Add one more. Shipping's on us at $50.",
     "Free US shipping over $50.",
     "Free Shipping $50+", "Reach free shipping",
     "Range", "Cart of products, overhead"),
    ("B-SHIP", "Easy math", "BOF",
     "Treat yourself + free shipping. Easy math.",
     "Spend $50, ship free across the US.",
     "Free Shipping $50+", "Build your order",
     "Bestsellers", "Bundle of bestsellers"),
    ("B-SHIP", "Almost there", "BOF",
     "Almost at $50? Your skin says go for it.",
     "Free US shipping when you hit $50.",
     "Free Shipping $50+", "Top up + ship free",
     "Range", "Products with progress cue"),
    ("B-SHIP", "Bestsellers", "BOF",
     "Bestsellers in. Shipping out — free.",
     "Orders $50+ ship free in the US.",
     "Free US Shipping $50+", "Shop bestsellers",
     "Hero SKUs", "Hero lineup flatlay"),
    ("B-SHIP", "Worth it", "BOF",
     "The glow's worth it. The shipping's free.",
     "Free US shipping over $50.",
     "Free Shipping $50+", "Shop the edit",
     "Range", "Styled product edit"),
    ("B-SHIP", "One order", "BOF",
     "Everything you've been eyeing. One order. Free shipping.",
     "$50+ ships free across the US.",
     "Free Shipping $50+", "Fill your cart",
     "Range", "Full flatlay of range"),
    ("B-SHIP", "Skip the fee", "BOF",
     "Skip the shipping fee, not the self-care.",
     "Free US shipping on $50+.",
     "Free Shipping $50+", "Shop now",
     "Range", "Self-care flatlay"),

    # --- ANGLE: HERO SKU SPOTLIGHT (bestseller social proof, no price) ---
    ("B-HERO", "10k showers", "BOF",
     "Meet the scrub 10,000 showers swear by.",
     "Our #1 coffee scrub — now in your routine.",
     "#1 Bestseller", "Shop the Coffee Scrub",
     "Coffee Scrub", "Hero jar, dramatic light"),
    ("B-HERO", "The one", "BOF",
     "The Coffee Scrub. The one everyone means.",
     "Cold-pressed coffee + raw sugar. Smoother in one wash.",
     "Bestseller", "Shop the hero",
     "Coffee Scrub", "Hero jar macro"),
    ("B-HERO", "Bedside aloe", "BOF",
     "The aloe gel that earns its spot by your bed.",
     "Cooling, fast-absorbing, endlessly reached-for.",
     "Bestseller", "Shop the Aloe Gel",
     "Aloe Gel", "Aloe tube on a nightstand"),
    ("B-HERO", "Back in stock", "BOF",
     "Sold out twice. Back for good.",
     "The Coffee Scrub everyone waited for.",
     "Back In Stock", "Get it now",
     "Coffee Scrub", "Jar with restock cue"),
    ("B-HERO", "Start here", "BOF",
     "If you buy one thing, make it this.",
     "The Coffee Scrub — where everyone starts.",
     "Start Here", "Shop the Coffee Scrub",
     "Coffee Scrub", "Hero jar, clean"),
    ("B-HERO", "Reviews", "BOF",
     "5 stars, 2,000+ times over.",
     "The Coffee Scrub our reviewers can't stop talking about.",
     "★★★★★ 2,000+ reviews", "See why",
     "Coffee Scrub", "Jar beside a review card"),
    ("B-HERO", "Does the most", "BOF",
     "The aloe gel that does the most by doing the least.",
     "One-ingredient hero. Endless uses.",
     "Bestseller", "Shop the Aloe Gel",
     "Aloe Gel", "Gel macro, minimalist"),
    ("B-HERO", "Worth the hype", "BOF",
     "Your shelf called. It wants the bestseller.",
     "The Coffee Scrub — the one worth the hype.",
     "#1 Bestseller", "Shop now",
     "Coffee Scrub", "Styled shelf with jar"),

    # --- ANGLE: GIFT SET / RATTAN (gifting conversion) ---
    ("B-GIFTSET", "Handled", "BOF",
     "Gifting, beautifully handled.",
     "The Rattan Valise set — wrapped and ready.",
     "Gift-Ready", "Shop the gift set",
     "Rattan Valise", "Valise gift, ribbon"),
    ("B-GIFTSET", "Looks expensive", "BOF",
     "The gift that arrives looking expensive.",
     "Hand-woven rattan, filled with bestsellers.",
     "Gift-Ready", "Shop gift sets",
     "Rattan Basket", "Basket gift overhead"),
    ("B-GIFTSET", "Covers all", "BOF",
     "One set. Every base covered.",
     "Exfoliate & Nourish Set — the gift that does it all.",
     "The Gift Set", "Shop the set",
     "Exfoliate & Nourish Set", "Set styled, editorial"),
    ("B-GIFTSET", "Keep basket", "BOF",
     "She'll keep the basket forever.",
     "Rattan keepsake + body care she'll actually use.",
     "Keepsake Gift", "Shop the basket",
     "Rattan Basket", "Basket close-up, texture"),
    ("B-GIFTSET", "Anniversary", "BOF",
     "Anniversary sorted in one click.",
     "The Rattan Valise — a gift that lasts past the date.",
     "Anniversary-Ready", "Shop the valise",
     "Rattan Valise", "Romantic gift styling"),
    ("B-GIFTSET", "Whole ritual", "BOF",
     "Give the whole ritual, not just a piece.",
     "Exfoliate & Nourish Set, ready to gift.",
     "Complete Gift", "Shop the set",
     "Exfoliate & Nourish Set", "Full set styled"),
    ("B-GIFTSET", "Where from", "BOF",
     "The 'where did you get that?' gift.",
     "Rattan, ribbon, and bestsellers inside.",
     "Gift-Ready", "Shop gift sets",
     "Rattan Valise", "Gift moment, hands"),
    ("B-GIFTSET", "Birthday", "BOF",
     "Birthdays handled, beautifully.",
     "A body care set worth unwrapping.",
     "Birthday Gift", "Shop the set",
     "Exfoliate & Nourish Set", "Birthday gift styling"),

    # --- ANGLE: SOCIAL PROOF (review-led conversion) ---
    ("B-PROOF", "Repurchased", "BOF",
     "\"I've repurchased four times.\"",
     "Find out what the fuss is about.",
     "★★★★★ Verified review", "Shop bestsellers",
     "Coffee Scrub", "Review card beside jar"),
    ("B-PROOF", "Smoothest", "BOF",
     "\"My legs have never been this smooth.\"",
     "Join thousands who made the switch.",
     "★★★★★ Verified", "Shop the scrub",
     "Coffee Scrub", "Smooth legs + quote overlay"),
    ("B-PROOF", "10k loved", "BOF",
     "10,000+ smoother showers and counting.",
     "See why the Coffee Scrub keeps selling out.",
     "Loved by 10,000+", "Join them",
     "Coffee Scrub", "Hero jar, social cue"),
    ("B-PROOF", "Actually finish", "BOF",
     "\"The only body product I actually finish.\"",
     "Real words from real skin.",
     "★★★★★", "Shop now",
     "Range", "Quote card, clean"),
    ("B-PROOF", "Rated 4.9", "BOF",
     "Rated 4.9. Earned, not bought.",
     "Thousands of reviews can't all be wrong.",
     "4.9 ★ rating", "See the reviews",
     "Coffee Scrub", "Jar + star rating"),
    ("B-PROOF", "Gifted obsessed", "BOF",
     "\"Gifted it. Now they're obsessed too.\"",
     "The body care that converts everyone.",
     "★★★★★", "Shop gifts",
     "Gift Set", "Gift + quote overlay"),

    # --- ANGLE: BIRTHDAY HOROSCOPE (15% off, sign-gated) ---
    ("B-ZODIAC", "Gemini", "BOF",
     "Happy birthday, Gemini. Here's 15% off.",
     "Use GEMINI15 — your glow deserves a gift too.",
     "15% Off · GEMINI15", "Treat yourself",
     "Bestsellers", "Celestial Gemini theme, products"),
    ("B-ZODIAC", "Cancer", "BOF",
     "It's your season, Cancer. Glow accordingly.",
     "15% off with CANCER15.",
     "15% Off · CANCER15", "Shop your birthday",
     "Range", "Celestial Cancer theme"),
    ("B-ZODIAC", "Leo", "BOF",
     "Leo season = your season. Take 15% off.",
     "Use LEO15. Self-gifting is written in the stars.",
     "15% Off · LEO15", "Treat yourself",
     "Range", "Celestial Leo theme"),
    ("B-ZODIAC", "Virgo", "BOF",
     "Virgo, you've earned a little softness.",
     "Use VIRGO15 on your birthday glow.",
     "15% Off · VIRGO15", "Shop now",
     "Range", "Celestial Virgo theme"),
    ("B-ZODIAC", "Generic code", "BOF",
     "The stars say: treat yourself. (15% off.)",
     "Your birthday code is waiting — [SIGN]15.",
     "Birthday 15% Off", "Claim your code",
     "Range", "Zodiac wheel motif"),
    ("B-ZODIAC", "Generic edit", "BOF",
     "A birthday glow, written in the stars.",
     "15% off your sign's season — use [SIGN]15.",
     "Birthday 15% Off", "Shop your birthday edit",
     "Bestsellers", "Celestial gifting scene"),
]

HEADERS = ["ad_id", "funnel", "angle", "concept", "headline",
           "subhead", "badge", "cta", "product", "visual"]


def rows():
    out = []
    for i, a in enumerate(ADS, start=1):
        angle, concept, funnel, headline, subhead, badge, cta, product, visual = a
        out.append({
            "ad_id": f"{funnel}-{i:03d}",
            "funnel": funnel,
            "angle": angle,
            "concept": concept,
            "headline": headline,
            "subhead": subhead,
            "badge": badge,
            "cta": cta,
            "product": product,
            "visual": visual,
        })
    return out


def write_csv(path, data):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADERS)
        w.writeheader()
        for r in data:
            w.writerow(r)


def write_matrix(path, data):
    mof = [r for r in data if r["funnel"] == "MOF"]
    bof = [r for r in data if r["funnel"] == "BOF"]
    lines = []
    lines.append("# CoBa's Daughter — Broad Static Ad Matrix (100 ads)\n")
    lines.append(f"**Funnel mix:** {len(mof)} MOF / {len(bof)} BOF  ·  "
                 "**Aspect:** 1:1 (master) + 9:16 (adapt)  ·  "
                 "**Font:** Plus Jakarta Sans\n")
    lines.append("> One promo per BOF ad. MOF ads carry a Reason-To-Believe, never a price.\n")
    current = None
    for r in data:
        if r["angle"] != current:
            current = r["angle"]
            lines.append(f"\n## {r['funnel']} · {r['angle']}\n")
            lines.append("| ID | Concept | Headline | Subhead | Badge (RTB/Offer) | CTA | Product | Visual |")
            lines.append("|----|---------|----------|---------|-------------------|-----|---------|--------|")
        lines.append("| {ad_id} | {concept} | {headline} | {subhead} | {badge} | {cta} | {product} | {visual} |"
                     .format(**{k: str(v).replace("|", "/") for k, v in r.items()}))
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    data = rows()
    assert len(data) == 100, f"Expected 100 ads, got {len(data)}"
    mof = sum(1 for r in data if r["funnel"] == "MOF")
    bof = sum(1 for r in data if r["funnel"] == "BOF")
    assert (mof, bof) == (40, 60), f"Expected 40/60, got {mof}/{bof}"
    write_csv(os.path.join(HERE, "bulk-create-1x1.csv"), data)
    write_csv(os.path.join(HERE, "bulk-create-9x16.csv"), data)
    write_matrix(os.path.join(HERE, "100-ads.md"), data)
    print(f"OK: {len(data)} ads  |  {mof} MOF / {bof} BOF")
    print("Wrote: bulk-create-1x1.csv, bulk-create-9x16.csv, 100-ads.md")


if __name__ == "__main__":
    main()
